### DISCUSSION TITLE
Loading PostCSS "purgecss" plugin failed: loadedPlugin is not a function when using .postcssrc.yml

### DISCUSSION THREAD

**Discussion by jackkemmish** [FullHuman/purgecss#1261] [Q&A]
Hi there, I am trying to use this as part of my `postcss` config, and we use a `yml` file to do this.

My current `yml` set up is:
```yaml
plugins:
    postcss-normalize: {}
    postcss-inline-svg:
        paths:
            - 'static/svg/'
    autoprefixer: {}
    purgecss:
        content:
            - './templates/**/*.ss'
```

However on build, I get this error: `Loading PostCSS "purgecss" plugin failed: loadedPlugin is not a function`.

Can someone shed some light what I might be doing wrong here??

Thanks,
Jack
