### DISCUSSION TITLE
How do combinators work?

### DISCUSSION THREAD

**Discussion by fostimus** [FullHuman/purgecss#893] [Q&A]
Let's say I have this HTML:
```html
<div class="parent"></div>
```

And my CSS is:
```css
.parent {
   background: yellow;
   width: 300px;
   height: 300px;
}

.parent .child {
   background: black;
   width: 100px;
   height: 100px;
}
```

Should `.parent .child` be removed from CSS? There is no child, so the CSS selector .parent .child doesn't exist.
