### ISSUE TITLE
Scoped HTML and body not removed

### ISSUE THREAD

**Issue by davidhouweling** [FullHuman/purgecss#109]
**Describe the bug**
I know it's probably not normal and isn't done in general, but I am building isolated components where all the SCSS is imported under 1 class name, for this example let's call it `.scope`. As all the CSS includes a `normalize.css` as well, HTML and body get defined as `.scope html` and `.scope body`. However, the component lives inside of the `<body />` and therefore those two definitions would never be met. These should be removed in my opinion.

**To Reproduce**
1. Using the following HTML
``` html
<html>
<body>
<div class="scope">
  <div class="component"></div>
</div>
</body>
</html>
```
2. With the following CSS
``` css
.scope html { color: red; }
.scope body { color: blue; }
.scope .component { color: black; }
.scope .non-existent { color: white; }
```
3. Pass these through the CLI
4. Generated CSS is:
``` css
.scope html { color: red; }
.scope body { color: blue; }
.scope .component { color: black; }
```

**Expected behavior**
CLI css output should be
``` css
.scope .component { color: black; }
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1709
 - Version of Purgecss: 1.0.1

**Additional context**
N/A
