### ISSUE TITLE
CSS attribute selectors not being removed

### ISSUE THREAD

**Issue by davidhouweling** [FullHuman/purgecss#110]
**Describe the bug**
As part of normalize.css, it uses attribute selectors as a means to select elements, however these get left in by purgecss.

**To Reproduce**
1. Using the following HTML
``` html
<html>
  <body>
    <div class="component"></div>
  </body>
</html>
```
2. With the following CSS
``` css
.component { color: black; }
button,
[type="button"],
[type="reset"],
[type="submit"] {
  -webkit-appearance: button;
}
```
3. Passing the above HTML and CSS through the CLI
4. The resulting CSS is as followed
``` css
.component { color: black; }
[type="button"],
[type="reset"],
[type="submit"] {
  -webkit-appearance: button;
}
```

**Expected behavior**
The generated CSS should be
``` css
.component { color: black; }
```

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Windows 10 version 1709
 - Version of Purgecss 1.0.1

**Additional context**
N/A
