### ISSUE TITLE
[Bug]: A `:hover` in a nested rule is reported as useless

### ISSUE THREAD

**Issue by regseb** [FullHuman/purgecss#1153]
### Describe the bug

A `:hover` in a nested rule is reported as useless.

### To Reproduce

- `package.json`

  ```JSON
  {
    "name": "testcase",
    "version": "1.0.0",
    "type": "module",
    "dependencies": {
      "purgecss": "5.0.0"
    }
  }
  ```

- `index.html`

  ```HTML
  <!doctype html>
  <html>
    <head>
      <meta charset="utf-8" />
      <title>Test case</title>
      <link href="style.css" rel="stylesheet" />
    </head>
    <body>
      <a href="https://github.com/">GitHub</a>
    </body>
  </html>
  ```

- `style.css`

  ```CSS
  a:hover {
    background-color: green;
  }

  a {
    &:hover {
      color: red;
    }
  }
  ```

1. `npm install`
2. `npx purgecss --css style.css --content index.html --rejected`

```JSON
[{
  "css": "a:hover {\n    background-color: green;\n}\n",
  "file": "style.css",
  "rejected": ["&:hover"]
}]
```

### Expected Behavior

```JSON
[{
  "css": "a:hover {\n    background-color: green;\n}\n\na {\n    &:hover {\n        color: red;\n    }\n}\n",
  "file": "style.css",
  "rejected": []
}]
```

### Environment

- Ubuntu: 22.04.3 LTS
- Node.js: v18.17.1
- npm: 9.8.1
- purgecss: 5.0.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by fongandrew** [comment]
For anyone coming across this (over a year later!), adding `&` to the safelist _seems_ to work?

```
npx purgecss --css style.css --content index.html --rejected --safelist "&"
```

I'm not sure I've thought through all the edge cases, but here's my test case:

```html
<!doctype html>
<html>
  <head>
    <meta charset="utf-8" />
    <title>Test case</title>
    <link href="style.css" rel="stylesheet" />
  </head>
  <body>
    <a class="foo">Hey <span class"bar">World</span></a>
    <a href="https://github.com/">Git<span>Hub</span></a>
  </body>
</html>
```

```css
a:hover {
  background-color: green;
}

a {
  &:hover {
    color: red;
  }

  &.foo {
    color: purple;
  }

  &.not-used {
    color: pink;
  }

  span {
    color: yellow;
  }
}

.foo {
  .bar {
    color: orange;
  }

  .not-used-nested {
    color: cyan;
  }
}

.not-used-parent {
  &:hover {
    color: blue;
  }
}
```

This gives `"rejected":["&.not-used",".not-used-nested",".not-used-parent"]`.
