### ISSUE TITLE
[Bug]: When variable is used with space after/before brackets their definition is not preserved.

### ISSUE THREAD

**Issue by pszczesniak** [FullHuman/purgecss#1264]
### Describe the bug

When there is a declared variable:
```css
:root {
	--foo: red;
}
```
and is used with some class, for example:
```css
.bar {
	color: var( --foo );
}
```

In the result the variable declaration is omitted.

All works fine when
```css
.bar {
	color: var(--foo);
}
```
I know that this is the most common case of how CSS vars are written in CSS code, but the specification does not prohibit the use of spaces.

### To Reproduce

Demo on StackBlitz: https://stackblitz.com/edit/stackblitz-starters-g6qdqe?file=index.js,output.css,input.css

### Expected Behavior

Used variable is preserved.

### Environment

Version: 6.0.0

### Add any other context about the problem here

context

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
