### ISSUE TITLE
[Bug]: Remove unused `@property` rules

### ISSUE THREAD

**Issue by filipsobol** [FullHuman/purgecss#1325]
### Describe the bug

With the `variables: true` configuration option, PurgeCSS can remove unused variables declared like this:

```css
:root {
  --tw-rotate-x: rotateX(0);
}
```

However, it doesn't remove the fairly recently introduced [`@property`](https://developer.mozilla.org/en-US/docs/Web/CSS/@property) rule like this:

```css
@property --tw-rotate-x-2 {
  syntax: '*';
  inherits: false;
  initial-value: rotateX(0);
}
```

### To Reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-ogqm14x7?file=style.css&terminal=dev
2. Run `npm run build` in the terminal.
3. Inspect the CSS file in the `dist/assets` folder.

### Expected Behavior

CSS variables declared using `@property` should be removed

### Environment

N/A

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct
