### ISSUE TITLE
Tags with the letter n in them are not purged

### ISSUE THREAD

**Issue by mdickopp** [FullHuman/purgecss#195]
Tags that have the letter `n` in them (e.g. `input`, `main`) are not purged.

Code to reproduce:

```js
const Purgecss = require('purgecss');

const purgecss = new Purgecss({
  content: [{
    raw: '<h1></h1>',
  }],
  css: [{
    raw: 'h1 { margin: 0; } h2 { margin: 0; } input { margin: 0; }'
  }]
});

console.log(purgecss.purge()[0].css);
```

Expected output:

```css
h1 { margin: 0; }
```

Actual output:

```css
h1 { margin: 0; } input { margin: 0; }
```

I think that the regular expression in line 328 in `src/index.js` might be the culprit, since it matches tags that have an `n` in them.
