### ISSUE TITLE
grunt-purgecss missing files

### ISSUE THREAD

**Issue by XhmikosR** [FullHuman/purgecss#293]
@Ffloriel it seems you used a package.json file from another package which had a `lib` folder but grunt-purgecss has a tasks folder. Also, I'm not sure if the other properties make sense in grunt-purgecsss like `main`, `module` etc.

Thanks in advance!

**Comment by Ffloriel** [comment]
Yes, the other properties do not make sense for grunt-purgecss. Released 2.1.1 for grunt-purgecss to fix this issue

**Comment by XhmikosR** [comment]
@Ffloriel Thanks! BTW I'd still keep the files property and just adapt it. No point in having the tests in production :)

**Comment by XhmikosR** [comment]
BTW is `@types/grunt` needed to be in dependencies?

**Comment by Ffloriel** [comment]
Yep, it's not needed. I'll rectify this :)

**Comment by XhmikosR** [comment]
Thanks! One issue I notice after upgrading the the latest version is one specific selector missing. Let me know if you want me to make a new issue abou it.

Basically, the following selector is missing with the new version:

```css
.full-news a[href*="//"]:not([href^="mpc-hc.org"]):not([href*="trac.mpc-hc.org"])::after,
.new a[href*="//"]:not([href^="mpc-hc.org"]):not([href*="trac.mpc-hc.org"])::after {
    content: "\f08e"; /* fa-external-link */
    display: inline-block;
    font-family: FontAwesome;
    margin-left: 0.3em;
}
```

If change the code to this then it's kept with the new version

```css
.full-news a:not([href*="mpc-hc.org"])::after,
.new a:not([href*="mpc-hc.org"])::after {
    content: "\f08e"; /* fa-external-link */
    display: inline-block;
    font-family: FontAwesome;
    margin-left: 0.3em;
}
```
