### ISSUE TITLE
Can't handle attribute pattern selector

### ISSUE THREAD

**Issue by bangzek** [FullHuman/purgecss#303]
purgecss doesn't understand attribute pattern selector like this one from bootstrap 4:

`.form-row > [class*="col-"]`

**Comment by emilio-martinez** [comment]
I ran into this issue as well—not within bootstrap, but I did notice attribute selectors being stripped.

**Comment by Jon-Salmon** [comment]
I am also experiencing this, but only when using a custom defaultExtractor

**Comment by Ffloriel** [comment]
do you have an example to reproduce the issue?

**Comment by jayvanhu** [comment]
@Ffloriel I'm not the original poster, but this other [issue](https://github.com/FullHuman/purgecss/issues/475) seems to be the same bug with a config for reproducing the issue

**Comment by divinerites** [comment]
I can confirm that I face the same issue. (Using Tailwind/PurgeCSS in Hugo).
The `[class^="tf-"], [class*=" tf-"] ` is removed from the css, while (for example) the used `tf-ion-ios-telephone` is well taken care of.

```css
[class^="tf-"], [class*=" tf-"] {
  /* use !important to prevent issues with browser extensions that change fonts */
  font-family: 'themefisher-font' !important;
  speak: none;
  font-style: normal;
  font-weight: normal;
  font-variant: normal;
  text-transform: none;
  line-height: 1;

  /* Better Font Rendering =========== */
  -webkit-font-smoothing: antialiased;
  -moz-osx-font-smoothing: grayscale;
}
```

```js
const theme = require('tailwindcss/defaultTheme');
const typography = require('@tailwindcss/typography');

//const colorBrand = 'var(--color-pretty)';

// Utils
const round = (num) => num.toFixed(7).replace(/(\.[0-9]+?)0+$/, '$1').replace(/\.0$/, '');
const rem = (px) => `${round(px / 16)}rem`;
const em = (px, base) => `${round(px / base)}em`;
const px = (px) => `${px}px`;

module.exports = {
	important: true, // See https://tailwindcss.com/docs/configuration#important
	experimental: {
		// See https://github.com/tailwindlabs/tailwindcss/pull/2159
		applyComplexClasses: true
	},
	purge: {
		enabled: process.env.HUGO_ENVIRONMENT === 'production',
		content: [ './hugo_stats.json' ],
		mode: 'all',
		options: {
			//whitelist: [ 'pl-1', 'pl-3' ],
			defaultExtractor: (content) => {
				let els = JSON.parse(content).htmlElements;
				els = els.tags.concat(els.classes, els.ids);
				return els;
			}
		}
	},
	plugins: [ typography ]
};
```

**Comment by xorock** [comment]
I've also experienced this bug (using laravel-mix-purgecss + tailwind).

```css
/* purgecss start ignore */
    input[type="submit"] {  /* this simple rule is ignored */
        color: red;
    }
    /*! purgecss end ignore */
```
But what's weird here, if I add "purgecss start/end ignore" comments, the resulting file size suddenly grows from 7kB to 1.48MB.
