### ISSUE TITLE
`:not` selector missing in 2.x

### ISSUE THREAD

**Issue by XhmikosR** [FullHuman/purgecss#356]
Originally reported in https://github.com/FullHuman/purgecss/issues/293#issuecomment-593420415

### When reporting a bug, please try to include the following:
- [ ] A descriptive title
- [ ] An *isolated* way to reproduce the behavior (example: GitHub repository with code isolated to the issue that anyone can clone to observe the problem)
- [ ] What package and version  you're using, and the platform(s) you're running it on: grunt-purgecss@2.1.1, purgecss@2.1.0

### When you open an issue for a feature request, please add as much detail as possible:
- [ ] A descriptive title
- [ ] A description of the problem you're trying to solve, including *why* you think this is a problem
- [ ] An overview of the suggested solution
- [ ] If the feature changes current behavior, reasons why your solution is better

```css
.full-news a[href*="//"]:not([href^="mpc-hc.org"]):not([href*="trac.mpc-hc.org"])::after,
.new a[href*="//"]:not([href^="mpc-hc.org"]):not([href*="trac.mpc-hc.org"])::after {
    content: "\f08e"; /* fa-external-link */
    display: inline-block;
    font-family: FontAwesome;
    margin-left: 0.3em;
}
```

If change the code to this then it's kept with the new version

```css
.full-news a:not([href*="mpc-hc.org"])::after,
.new a:not([href*="mpc-hc.org"])::after {
    content: "\f08e"; /* fa-external-link */
    display: inline-block;
    font-family: FontAwesome;
    margin-left: 0.3em;
}
```
