### ISSUE TITLE
Attribute selector with space is being remove

### ISSUE THREAD

**Issue by Akumzy** [FullHuman/purgecss#392]
Attribute selectors with space are being removed like
## Code
``` CSS
[class*=' icon-'],
[class^='icon-'] {
  font-family: 'icomoon' !important;
}
```
## Expected Behaviour 
``` CSS
[class*=' icon-'],
[class^='icon-'] {
  font-family: 'icomoon' !important;
}
```
## Actual Behaviour

``` CSS
[class^='icon-'] {
  font-family: 'icomoon' !important;
}
```
