### ISSUE TITLE
whitelistPatternsChildren regex not working as expected

### ISSUE THREAD

**Issue by jmooring** [FullHuman/purgecss#466]
Objective: retain the `.amp-img.cover img` selector in the final css.

css:

```css
.amp-img.cover img {
  object-fit: cover; /* Crops the image to cover the containing element. */
}
```
purgecss.config.js (FAILS):

```js
module.exports = {
  whitelistPatternsChildren: [/\.amp-img\.cover$/]
}
```

purgecss.config.js (WORKS):

```js
module.exports = {
  whitelistPatternsChildren: [/cover$/]
}
```

What am I doing wrong? I have also tried escaping the backslashes by specifying `whitelistPatternsChildren: [/\\.amp-img\\.cover$/]`.

I am using the CLI.
