### ISSUE TITLE
PurgeCss does not recognize keyframes that used as CSS custom properties (variables) value

### ISSUE THREAD

**Issue by hsnaydd** [FullHuman/purgecss#478]
PurgeCss deletes the keyframe even though it is used;

```scss
.component {
  animation: var(--component-animation)
}

.component--animated {
  --component-animation: fadeIn 0.4s;
}

@keyframes fadeIn {
  from {
    opacity: 0;
  }

  to {
    opacity: 1;
  }
}
```
