### ISSUE TITLE
Unused @keyframes not removed at all

### ISSUE THREAD

**Issue by hjkcai** [FullHuman/purgecss#51]
Here is the minimal reproduce:

test.css

```css
@-webkit-keyframes AAAAAAAAAAAAAAAAAAA {
  0% { color: red; }
  100% { color: #fff; }
}

@keyframes AAAAAAAAAAAAAAAAAAA {
  0% { color: red; }
  100% { color: #fff; }
}
```

empty.html

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Document</title>
</head>
<body>

</body>
</html>
```

Command line:

```bash
npx purgecss --css test.css --content empty.html -o dist
```

The resulting `dist/test.css` should be empty. But its content is exactly the same to the original file. 

purgecss version: 0.20.0
