### ISSUE TITLE
question/feature_request(parsing): get solely values of “id” and “class” attributes from HTML files

### ISSUE THREAD

**Issue by Kristinita** [FullHuman/purgecss#515]
### 1. Summary

**If** I have the same class name and text as in the example:

```html
<p>KiraClass</p>
```

```css
.KiraClass {
    color: yellow
}
```

PurgeCSS not delete the unused class (`.KiraClass` in the example).

### 2. MCVE

You can see this configuration in the [**`KiraPurgeCSS` branch**](https://github.com/Kristinita/SashaGruntDebugging/tree/KiraPurgeCSS) of my demo/debugging repository.

1. The part of the `package.json`:

    ```json
    "devDependencies": {
      "coffeescript": "^2.5.1",
      "grunt": "^1.3.0",
      "grunt-purgecss": "^3.0.0"
    }
    ```

1. `Gruntfile.coffee`:

    ```coffee
    module.exports = (grunt) ->

        grunt.loadNpmTasks 'grunt-purgecss'

        grunt.initConfig

            purgecss:
                kiratarget:
                    options:
                        content: ["KiraGoddess.html"]
                    files:
                        "KiraGoddess.css": ["KiraGoddess.css"]
    ```

1. `KiraGoddess.html`:

    ```html
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <title>PurgeCSS debugging</title>
        <link rel="stylesheet" href="KiraGoddess.css">
    </head>
    <body>
        <p class="KiraFirst">KiraScond</p>
    </body>
    </html>
    ```

1. `KiraGoddess.css`:

    ```css
    .KiraFirst {
        color: red
    }

    .KiraSecond {
        color: yellow
    }
    ```

1. The part of the `.travis.yml`:

    ```yaml
    install:
    - npm i -g grunt-cli purgecss
    - npm i

    script:
    - purgecss --css KiraGoddess.css --content KiraGoddess.html
    - grunt purgecss --verbose --stack
    - cat KiraGoddess.css
    ```

#### 3.1. Expected

1. [**CLI**](https://travis-ci.com/github/Kristinita/SashaGruntDebugging/builds/199259385#L214):

    ```json
    [
        {
            "css": ".KiraFirst {\n\tcolor: red\n}\n",
            "file": "KiraGoddess.css"
        }
    ]
    ```

1. [**Grunt**](https://travis-ci.com/github/Kristinita/SashaGruntDebugging/builds/199259385#L247-L249):

    ```css
    .KiraFirst {
        color: red
    }
    ```

PurgeCSS delete an unused class.

#### 3.2. Unexpected

**If**:

```diff
--- <p class="KiraFirst">KiraScond</p>
+++ <p class="KiraFirst">KiraSecond</p>
```

I have the text `KiraSecond` in the `KiraGoddess.html` and the unused class `.KiraSecond` in the `KiraGoddess.css`.

1. [**CLI**](https://travis-ci.com/github/Kristinita/SashaGruntDebugging/builds/199259801#L214):

    ```json
    [
        {
            "css": ".KiraFirst {\n\tcolor: red\n}\n\n.KiraSecond {\n\tcolor: yellow\n}\n",
            "file": "KiraGoddess.css"
        }
    ]
    ```

1. [**Grunt**](https://travis-ci.com/github/Kristinita/SashaGruntDebugging/builds/199259801#L247-L253):

    ```css
    .KiraFirst {
        color: red
    }

    .KiraSecond {
        color: yellow
    }
    ```

PurgeCSS doesn’t remove an unused class.

#### 4.1. purgecss.config.js

1. `purgecss.config.js` (as in “[**Using an extractor**](https://purgecss.com/extractors.html#using-an-extractor)” section):

    ```js
    import purgeHtml from 'purge-from-html';

    const options = {
      extractors: [
        {
          extractor: purgeHtml,
          extensions: ['html']
        }
      ]
    };

    export default options;

    ```

1. New `Gruntfile.coffee`:

    ```coffee
    module.exports = (grunt) ->

        grunt.loadNpmTasks 'grunt-purgecss'

        grunt.initConfig

            purgecss:
                kiratarget:
                    options:
                        config: "purgecss.config.js"
                        content: ["KiraGoddess.html"]
                    files:
                        "KiraGoddess.css": ["KiraGoddess.css"]

    ```

No effect.

#### 4.2. custom extractor

In the [**example**](https://purgecss.com/plugins/grunt.html#the-purgecss-task), how use PurgeCSS + Grunt was shown a custom extractor. I don’t need to write a new HTML parser; it would be nice to have a default parser for pure HTML without templates that get values from classes and ids, not from all HTML.

Also, I couldn’t find any information, how use Grunt + [**purgecss-from-html**](https://github.com/FullHuman/purgecss/tree/master/packages/purgecss-from-html) extractor.

### 5. Environment

1. Operating system:

    1. Windows 10.0.19041.508 Pro N for Workstations 64-bit EN
    1. Ubuntu 20.04.1 LTS (Travis CI)

1. Grunt:

    1. grunt-cli v1.3.2
    1. grunt v1.3.0

1. PurgeCSS:

    1. CLI 1.4.2
    1. grunt-purgecss 3.0.0

Thanks.

**Comment by Ffloriel** [comment]
The Grunt file will not used the purgecss-config, that should be the cause of this error.

Here's the Gruntfile that I used to make this work:
```js
const purgeHtml = require('purgecss-from-html')

module.exports = grunt => {

	// Project configuration.
	grunt.initConfig({
	  // Configuration to be run (and then tested).
	  purgecss: {
		simple: {
		  options: {
			content: ['KiraGoddess.html'],
			extractors: [
				{
					extractor: purgeHtml,
					extensions: ['html']
				}
			]
		  },
		  files: {
			'KiraGoddess.css': ['KiraGoddess.css']
		  }
		}
	  }
	});

	grunt.loadNpmTasks('grunt-purgecss');

	grunt.registerTask('default', ['purgecss']);

  };
```

Result is:
```css
.KiraFirst {
	color: red
}
```
