### ISSUE TITLE
CSS Variables Order

### ISSUE THREAD

**Issue by lemmon** [FullHuman/purgecss#518]
I've noticed that PurgeCSS removes variables even though they are used if they are not in "proper" order.

```css
:root {
  --color: var(--default);
  --yellow: #ffdc00;
  --extra: yellow;
  --default: #0074d9;
}

.blue {
  color: var(--color);
}

.yellow {
  color: var(--yellow);
}
```

In this example the `--default` variable gets deleted since it is only defined *after* the `--color` variable. If I put `--default` before `--color` everythign works.

PurgeCSS v3.0.0

**Comment by ImanMh** [comment]
I have the same issue. I assume this is not fixed yea? or maybe I'm doing something wrong.

**Comment by jrencz** [comment]
I can confirm this happens in purgecss 4.1.3 as well.

In case I try 

```scss
/* other declarations */
.foo {
   .bar {
      --some-var: 1;
      @media (/*anything*/) {
        -- some-var: 2;
      }
   }
}
```

I end up with 

```css
@media (/*anything*/) {
  .foo .bar {
    -- some-var: 2;
  }
}
/* other declarations */
.foo .bar {
  --some-var: 1;
}
```

Instead of expected
```css
/* other declarations */
.foo .bar {
  --some-var: 1;
}
@media (/*anything*/) {
  .foo .bar {
    -- some-var: 2;
  }
}
```

But when I add something that won't change the semantics, like `content: ''` then the order is as expected
