### ISSUE TITLE
Remove non used selectors from grouped selector separated by comma.

### ISSUE THREAD

**Issue by alannungaray** [FullHuman/purgecss#527]
# Remove unused selectors from grouped selector separated by comma.

When a feature like @ extend SCSS is used a selector ends like this

```scss
.unused_helper_class {
  background-color: #fee;
}

.used_class {
  @extend .unused_helper_class ;
  border-width: 3px;
}
```
the  actual result is this 
```scss
.unused_helper_class, .used_class  {
  background-color: #fee;
}
.used_class{
  border-width: 3px;
}
```
if the new compiled code would like this 
```scss
.used_class  {
  background-color: #fee;
}
.used_class{
  border-width: 3px;
}
```

That would be awesome because developers could create a semantic user interface without conflicts with the original CSS frameworks and compact results without touching HTML files and correct style error on the style files. Example case
 
```scss
@import '../tailwind';
.profile_image_avatar{
 @extend w-32;
 @extend h-32; 
 @extend rounded-full;
 @extend mx-auto;
}
```

```scss
@import 'bootstrap'
.profile_image_avatar{
   with:32px;
   height:32px;
 @extend rounded-circle 
 @extend mx-auto
}
```
If for some reason the project  change the framework or do any style changes and the HTML is already deployed it's only necessary to change a style file to do it also avoid conflicts with any other framework instance because the result it's like custom CSS without any footprint of the original library.

Please if you need more examples or use cases comment it instead close the issue. I really consider that feature  is the missing piece of to make the PurgeCSS the perfect tool

**Comment by Ffloriel** [comment]
PurgeCSS does not make any transformation on the CSS files.
Any transformation can be done with tools like postCSS. Once done, PurgeCSS can be use (with postcss-purgecss for example).
In:
```css
.unused_helper_class, .used_class  {
  background-color: #fee;
}
.used_class{
  border-width: 3px;
}
```
`.unused_helper_class` will be removed if unused.
