### ISSUE TITLE
Removes the media query content, but not the media query definition

### ISSUE THREAD

**Issue by samtrion** [FullHuman/purgecss#561]
I have an app which is based on TailwindCSS and Mobile First Media Queries. I have the situation, where some media query definitions are empty because I am not using any of the media query specific selectors.

Example:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

.blazor-error-ui { // This is the only class used so far
    @apply text-white;
}
```

Expected:
```css
... preflight / normalize deleted

.blazor-error-ui {
  --tw-text-opacity: 1;
  color: rgba(245, 130, 32, var(--tw-text-opacity));
}
```

Result:
```css
... preflight / normalize deleted

.blazor-error-ui {
  --tw-text-opacity: 1;
  color: rgba(245, 130, 32, var(--tw-text-opacity));
}

@media (min-width: 640px);

@media (min-width: 768px);

@media (min-width: 1024px);

@media (min-width: 1280px);

@media (min-width: 1536px)
```

package.json
```json
{
  "name": "Example",
  "version": "1.0.0",
  "devDependencies": {
    "autoprefixer": "^10.1.0",
    "gulp": "^4.0.2",
    "gulp-cli": "^2.3.0",
    "gulp-clone": "^2.0.1",
    "gulp-cssnano": "^2.1.3",
    "gulp-notify": "^3.2.0",
    "gulp-plumber": "^1.2.1",
    "gulp-postcss": "^9.0.0",
    "gulp-purgecss": "^3.1.3",
    "gulp-rename": "^2.0.0",
    "gulp-sourcemaps": "^3.0.0",
    "merge-stream": "^2.0.0",
    "postcss": "^8.2.2",
    "postcss-focus": "^5.0.1",
    "postcss-mixins": "^7.0.2",
    "postcss-preset-env": "^6.7.0",
    "postcss-simple-vars": "^6.0.2",
    "postcss-sort-media-queries": "^2.3.17",
    "precss": "^4.0.0",
    "purgecss": "^3.1.3",
    "tailwindcss": "^2.0.2"
  }
}
```

**Comment by samtrion** [comment]
Extended usage

```css
@tailwind base;
@tailwind components;
@tailwind utilities;

.blazor-error-ui {
    @apply text-white sm:text-orange;
}
```

Expected:
```css
... preflight / normalize deleted

.blazor-error-ui {
  --tw-text-opacity: 1;
  color: rgba(255, 255, 255, var(--tw-text-opacity));
}

@media (min-width: 640px) {
  .blazor-error-ui {
    --tw-text-opacity: 1;
    color: rgba(245, 130, 32, var(--tw-text-opacity));
  }
}
```

Result:
```css
... preflight / normalize deleted

.blazor-error-ui {
  --tw-text-opacity: 1;
  color: rgba(255, 255, 255, var(--tw-text-opacity));
}

@media (min-width: 640px) {
  .blazor-error-ui {
    --tw-text-opacity: 1;
    color: rgba(245, 130, 32, var(--tw-text-opacity));
  }
}

@media (min-width: 768px);

@media (min-width: 1024px);

@media (min-width: 1280px);

@media (min-width: 1536px)
```
