### ISSUE TITLE
Whitelisting parent selector & with attribute, still gets purged

### ISSUE THREAD

**Issue by Hirbod** [FullHuman/purgecss#645]
**Describe the bug**
I tried hundred combinations to prevent purging stuff like this:

```scss
.myClass {
    html[lang='fr'] & {
        bottom: 10vh;
    }
}
```

which will transpile to

```scss
html[lang=fr] {
    .myClass {
        bottom: 10vh;
    }
}
```

Whatever I tried, it got purged out of my code.
I even wrapped the comments around it and it still got purged.

```scss
/*! purgecss start ignore */
/*! purgecss end ignore */
```

Can someone tell me if that is a bug or what setting I have to use in order to prevent purging here?

**Environment (please complete the following information):**
- Newest version
- Everywhere
