### ISSUE TITLE
Doesn't work with Yarn 2

### ISSUE THREAD

**Issue by romeerez** [FullHuman/purgecss#669]
**Describe the bug**
When trying to launch project with yarn 2 pnp:

Error: @fullhuman/postcss-purgecss tried to access postcss, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.

**To Reproduce**
Use yarn 2 and @fullhuman/postcss-purgecss
```
npm i -g yarn
yarn set version berry
```

**Environment (please complete the following information):**
 - OS: Linux
 - Package postcss-purgecss
 - Version 3.1.3

**Additional context**
Trying to setup tailwind with create-react-app and to do it in yarn workspace.
With yarn 1 it works without errors.

I found similar issue of other library: https://github.com/styled-components/styled-components/issues/3082, fix is applicable here too:

Add to `.yarnrc.yml`
```yml
packageExtensions:
  "@fullhuman/postcss-purgecss@*":
    dependencies:
      "postcss": "*"
```
And run `yarn` after the change
