### ISSUE TITLE
Single css property gets removed during purge

### ISSUE THREAD

**Issue by dgrigg** [FullHuman/purgecss#699]
PurgeCss is removing properties from classes even though the entire class is not being purged.

I'm using postcss-nested to handle nested css.  The following two examples result in the same output when not using purgecss. When purgescss runs, the css from the first example results in a missing property

### Example 1
```
.point {
   position: relative;
   width: 0px;
   height: 0px;

  .flag {
      position: absolute;
      top: 0;
      left: 0;
   }
}
```

### Example 2
```
.point {
   position: relative;
   width: 0px;
   height: 0px;
}

.point .flag {
      position: absolute;
      top: 0;
      left: 0;
   }
}
```

### Expected output
```
.point { position: relative;  width: 0px;   height: 0px; }
.point .flag { position: absolute; top: 0;  left: 0; }
```

### Example 1 output when PurgeCss runs 
the position property on .point .flag has been removed
```
.point { position: relative;  width: 0px;   height: 0px; }
.point .flag { top: 0;  left: 0; }
```

### Example 2 output when PurgeCss runs 
This is the expected output
```
.point { position: relative;  width: 0px;   height: 0px; }
.point .flag { position: absolute; top: 0;  left: 0; }
```

**Comment by Ffloriel** [comment]
PurgeCSS shouldn't have any effect on the CSS properties.
Could you provide a minimal repository reproducing this issue?

**Comment by dgrigg** [comment]
I will try to put something together but the code in the original comment shows exactly the code and what has happening. To add to that I'm using TailwindCss. This is the Postcss config 
```
require('tailwindcss'),
require('postcss-nested'),
require('autoprefixer'),
```

**Comment by dgrigg** [comment]
@Ffloriel I just had this same issue happen on another project

### CSS
```
div.box {
    @apply w-3 h-3 border border-gray-900 flex items-center justify-center m-0;

    &::after {
      content: "";
      @apply border-white border-2 bg-green-500 hidden w-full h-full;
    }
}
input[type="checkbox"]:checked + div.box::after {
   @apply block;
}
```

### Result in dev mode
```
.checkbox div.box {
   margin: 0px;
   display: flex;
   height: 0.75rem;
   width: 0.75rem;
   align-items: center;
   justify-content: center;
   border-width: 1px;
   --tw-border-opacity: 1;
   border-color: rgba(45, 45, 45, var(--tw-border-opacity));
}

.checkbox div.box::after {
   content: "";
   display: none;
   height: 100%;
   width: 100%;
   border-width: 2px;
   --tw-border-opacity: 1;
   border-color: rgba(255, 255, 255, var(--tw-border-opacity));
   --tw-bg-opacity: 1;
   background-color: rgba(158, 189, 112, var(--tw-bg-opacity));
}

.checkbox input[type="checkbox"]:checked + div.box::after {
   display: block;
}

```


### Result in production mode
```
.checkbox div.box{
   margin:0;
   display:flex;
   height:.75rem;
   width:.75rem;
   align-items:center;
   justify-content:center;
   border-width:1px;
   --tw-border-opacity:1;
   border-color:rgba(45,45,45,var(--tw-border-opacity));
   content:"";
   display:none;
   height:100%;
   width:100%;
   border-width:2px;
   border-color:rgba(255,255,255,var(--tw-border-opacity));
   --tw-bg-opacity:1;
   background-color:rgba(158,189,112,var(--tw-bg-opacity));
}
```

In the production mode result the psuedo after element has been removed and the styles for it have ended up on the .box class. It looks like purgecss is having issues with elements that have styles defined and then have a child selector inside the {} with their own styles.

If I rewrite the original css to remove the automatic nesting and do it manually then everything outputs as expected.
```

.checkbox div.box {
  @apply w-3 h-3 border border-gray-900 flex items-center justify-center m-0;
}

.checkbox div.box::after {
  content: "";
  @apply border-white border-2 bg-green-500 hidden w-full h-full;
}

input[type="checkbox"]:checked + div.box::after {
  @apply block;
}
```

You should be able to replicate that locally with some simple nested css using this code.

**Comment by caschbre** [comment]
I'm running into a similar situation.  I'm using postcss-preset-env with nesting enabled.

The following does **not** work.
```css
    &[dna-labeldisplay='float'] {

      /* NOTE THE CHANGE HERE */
      &[dna-floating],
      &:focus-within {
        & .dna-label__text {
      /* END */
          @apply scale-90 translate-y-0 top-px;

          --tw-translate-x: 0;
          --tw-scale-x: 0.815;
          --tw-scale-y: 0.815;

          @nest [dna-size='sm']& {
            @apply -translate-y-4;
          }

          @nest [dna-size='lg']& {
            @apply translate-y-1;
          }
        }
      }
    }
```

However the following does work.
```css
    &[dna-labeldisplay='float'] {

      /* NOTE THE CHANGE HERE */
      &[dna-floating] .dna-label__text,
      &:focus-within .dna-label__text {
      /* END */
        @apply scale-90 translate-y-0 top-px;

        --tw-translate-x: 0;
        --tw-scale-x: 0.815;
        --tw-scale-y: 0.815;

        @nest [dna-size='sm']& {
          @apply -translate-y-4;
        }

        @nest [dna-size='lg']& {
          @apply translate-y-1;
        }
      }
    }
```

**Comment by Ffloriel** [comment]
I'm unable to reproduce this issue. Could you provide a repo to reproduce it if you have this issue again.
```css
div.box {
    margin: 0px;
    display: flex;
    height: 0.75rem;
    width: 0.75rem;
    align-items: center;
    justify-content: center;
    border-width: 1px;
    --tw-border-opacity: 1;
    border-color: rgba(45, 45, 45, var(--tw-border-opacity));

    &::after {
        content: "";
        display: none;
        height: 100%;
        width: 100%;
        border-width: 2px;
        --tw-border-opacity: 1;
        border-color: rgba(255, 255, 255, var(--tw-border-opacity));
        --tw-bg-opacity: 1;
        background-color: rgba(158, 189, 112, var(--tw-bg-opacity));
    }
}
input[type="checkbox"]:checked + div.box::after {
    display: block;
}
```
Here's the result with PurgeCSS 4.1.1 with postcss-nested:
```css
div.box {
  --tw-border-opacity: 1;
  align-items: center;
  border-color: rgba(45, 45, 45, var(--tw-border-opacity));
  border-width: 1px;
  display: flex;
  height: 0.75rem;
  justify-content: center;
  margin: 0;
  width: 0.75rem;
}
div.box:after {
  --tw-border-opacity: 1;
  --tw-bg-opacity: 1;
  background-color: rgba(158, 189, 112, var(--tw-bg-opacity));
  border-color: rgba(255, 255, 255, var(--tw-border-opacity));
  border-width: 2px;
  content: "";
  display: none;
  height: 100%;
  width: 100%;
}
input[type="checkbox"]:checked + div.box:after {
  display: block;
}
/*# sourceMappingURL=index.df7eb49a.css.map */

and with postcss-preset-env:
```css
div.box {
  --tw-border-opacity: 1;
  align-items: center;
  border-color: rgba(45, 45, 45, var(--tw-border-opacity));
  border-width: 1px;
  display: flex;
  height: 0.75rem;
  justify-content: center;
  margin: 0;
  width: 0.75rem;
}
div.box:after {
  --tw-border-opacity: 1;
  --tw-bg-opacity: 1;
  background-color: rgba(158, 189, 112, var(--tw-bg-opacity));
  border-color: rgba(255, 255, 255, var(--tw-border-opacity));
  border-width: 2px;
  content: "";
  display: none;
  height: 100%;
  width: 100%;
}
input[type="checkbox"]:checked + div.box:after {
  display: block;
}
/*# sourceMappingURL=index.df7eb49a.css.map */
```
