### ISSUE TITLE
PurgeCSS stops ignoring after an end comment

### ISSUE THREAD

**Issue by ddm-dano** [FullHuman/purgecss#701]
**Describe the bug**
I have the problem that when I use PurgeCSS together with PostCSS Import, that when I start with /*! purgecss start ignore */ a file is imported in which another ignore block ends with an end block, the start block above it is also closed.

**To Reproduce**
`one.css`
```css
/*! purgecss start ignore */

@import 'second.css';

.class-one {
  color: #111;
}

.class-one:hover {
  color: #444;
}

/*! purgecss end ignore */
```

`second.css`
```css
/*! purgecss start ignore */

.class-two {
 color: #fef;
}

/*! purgecss end ignore */
```

returns

```css
.class-two {
 color: #fef;
}

.class-one {
 color: #111;
}
```

**Expected behavior**
```css
.class-two {
 color: #fef;
}

.class-one {
 color: #111;
}

.class-one:hover {
  color: #444;
}
```

**Environment (please complete the following information):**
 - OS: Windows 10 64-Bit
 - Package purgecss from tailwind
 - Version 4.0.3

**Additional context**

**Comment by Ffloriel** [comment]
It's following the imports. When importing it will becomes:
```css
/*! purgecss start ignore */

/*! purgecss start ignore */

.class-two {
 color: #fef;
}

/*! purgecss end ignore */

.class-one {
  color: #111;
}

.class-one:hover {
  color: #444;
}

/*! purgecss end ignore */
```

The first `end ignore` comment is terminating the `start ignore` comment. It works like comments in html
```html
<!--
<!--
Write your comments here

-->
-->
```
