### ISSUE TITLE
Removes pseudo-element when selector is not found

### ISSUE THREAD

**Issue by cmizzi** [FullHuman/purgecss#71]
I just parsed my CSS stylesheet and found that some selectors are not cleaned up correctly. For example, I'm using Tailwindcss with Font-Awesome 5. I've got this kind of value as I'm not currently using them in my templates : 

```css
.fa-y-combinator:before {
content: "\f23b"
}

.fa-yahoo:before {
content: "\f19e"
}

.fa-yandex:before {
content: "\f413"
}

/* ... */ 

.sm\:hover\:font-medium:hover {
	font-weight: 500
}

.sm\:hover\:font-semibold:hover {
	font-weight: 600
}

.sm\:hover\:font-bold:hover {
	font-weight: 700
}
```
As the main selector (for example `.fa-yandex`) is not used, the `.fa-yandex:before` should be removed as well. I am looking wrong ?
