### ISSUE TITLE
The method of  Purgecss tree-shaking is incorrect

### ISSUE THREAD

**Issue by MissFlower** [FullHuman/purgecss#781]
**Describe the bug**
The method of  Purgecss tree-shaking is incorrect

**To Reproduce**
1. html css
```html
<div id="app">message</div>
```
```css
#app {
  width: 100%;
  height: 100%;
  font-size: 24px;
  color: red;
  text-align: center;
}

.message {
  color: black;
  font-size: 50px;
}
```
**Expected behavior**
For the above code，I expected get code is 
```css
#app {
  width: 100%;
  height: 100%;
  font-size: 24px;
  color: red;
  text-align: center;
}
```
but get
```css
#app {
  width: 100%;
  height: 100%;
  font-size: 24px;
  color: red;
  text-align: center;
}

.message {
  color: black;
  font-size: 50px;
}
```
This is because the HTML contains the message field，if I removed the message field, I can get the right tree-shake code
```css
#app {
  width: 100%;
  height: 100%;
  font-size: 24px;
  color: red;
  text-align: center;
}
```
**Environment (please complete the following information):**
 - OS: [windows 10]
 - Package [
 - "devDependencies": {
    "clean-webpack-plugin": "^4.0.0",
    "css-loader": "^6.5.0",
    "html-webpack-plugin": "^5.5.0",
    "mini-css-extract-plugin": "^2.4.3",
    "purgecss-webpack-plugin": "^4.0.3",
    "style-loader": "^3.3.1",
    "webpack": "^5.60.0",
    "webpack-cli": "^4.9.1",
    "webpack-dev-server": "^4.4.0"
  }
]
 - Version [4.0.3]

I hope this problem can be solved early, thanks
