### ISSUE TITLE
Problem with reading selectors such as :hover and :active in combination with postcss-preset-env

### ISSUE THREAD

**Issue by brechtDR** [FullHuman/purgecss#795]
**Describe the bug**
When working with the postcss-preset-env, purgecss seems to remove nested `:hover` and `:active` selectors.
While this is in combination with another plugin, it would be nice that this works in the scope of future css specs.

**To Reproduce**
1. Enable nesting in the postcss-preset-env
2. Execute PurgeCSS after it

example config:
```
plugins: [
        postcssPresetEnv({
            stage: 0,
            browsers: 'last 2 versions',
            autoprefixer: { grid: true },
            features: {
                'nesting-rules': true,
            }
        }),
        purgeCSS({
            enabled: true,
            content: ['./src/templates/**/*.twig'],
            whitelist: [
                'active',
            ],
            whitelistPatterns: [/js\-/, /badge\-/, /alert\-/],
        }),
    ]
```

Add a link to the page such as `<a href="#"><span class="icon"></span>some link</a>`

and add the following css to a css file:
```
a {
    display: flex;
    color: green;
    border-radius: 5px;
    &:hover {
        color: red;
        @media (width < 500px) {
            color: darkred;
        }
    }
    & .icon {
        color: yellow;
    }
}
```

The output is the following:
```
a {
    display: -webkit-box;
    display: -ms-flexbox;
    display: flex;
    color: green;
    border-radius: 5px
}

a .icon {
        color: yellow;
    }
```

**Expected behavior**
The hover states are also included in the Output css

**Environment (please complete the following information):**
 - Ppostcss-purgecss, postcss-preset-env
 - Versions: 4.0.5 for postcss and 1.7.0 for preset-env

** note **
It works perfectly with the preset-env without purging.

**Comment by Ffloriel** [comment]
The result with v4.1.1 is:
```css
a {
  border-radius: 5px;
  color: green;
  display: -webkit-box;
  display: -ms-flexbox;
  display: flex;
}
a:hover {
  color: red;
}
@media (max-width: 499px) {
  a:hover {
    color: darkred;
  }
}
a .icon {
  color: #ff0;
}
/*# sourceMappingURL=index.c7c40765.css.map */
```

Could you provide a repository with the issue if you still have it?
