### ISSUE TITLE
Tailwind v3 extractor

### ISSUE THREAD

**Issue by frederikhors** [FullHuman/purgecss#796]
**Is your feature request related to a problem? Please describe.**
Now that Tailwind 3 is really close I think we should update Docs for a custom Tailwind extractor that works.

**Describe the solution you'd like**
With Tailwind 2 we could have used a default extractor that they made available in an internal file, but it was not a public API and in fact it is gone now: https://github.com/tailwindlabs/tailwindcss/discussions/6162.

What to do with Tailwind 3?

Using extractor copied from Tailwind internals changes code from this:

```css
*,
:after,
:before {
	border: 0 solid;
	box-sizing: border-box;
}
:after,
:before {
	--tw-content: "";
}
```

to this

```css
* {
	border: 0 solid;
	box-sizing: border-box;
}
```

which is totally wrong (especially for Tailwind 3).

![image](https://user-images.githubusercontent.com/41120635/142771407-fb57aff2-37e7-487b-b610-7e79b6d6e950.png)

**Comment by frederikhors** [comment]
Using extractor copied from Tailwind internals changes code from this:

```css
*,
:after,
:before {
	border: 0 solid;
	box-sizing: border-box;
}
:after,
:before {
	--tw-content: "";
}
```

to this

```css
*,
:after,
:before {
	border: 0 solid;
	box-sizing: border-box
}

:after,
:before {
	--tw-content: ""
}
```

which is totally wrong (especially for Tailwind 3).
