### ISSUE TITLE
Nested custom properties bug

### ISSUE THREAD

**Issue by fexblanco** [FullHuman/purgecss#798]
**Describe the bug**

PurgeCSS breaks css custom properties when they are nested and the `variables` flag setted to true.

```js
postcss({
  plugins: [
    purgecss({
      ...
      variables: true
    })
  ]
}),
```

```css
/* style.css */
:root {
  --var1: 1px;
  --var2: var(--var1)
}
```

Is compiled to:

```css
 :root {
  --var2: var(--var1)
}
```

**Expected behavior**

```css
 :root {
  --var1: 1px;
  --var2: var(--var1)
}
```

or 

```css
 :root {
  --var1: 1px;
  --var2: 1px;
}
```

**Comment by Ffloriel** [comment]
fixed in 4.1.0
```css
:root {
    --var1: 1px;
    --var2: var(--var1)
}

.used {
    margin: var(--var2);
}
```
will results in
```css
:root {
    --var1: 1px;
    --var2: var(--var1)
}

.used {
    margin: var(--var2);
}
```
