### ISSUE TITLE
[Bug]: Purges pug inline classes declared before "&attributes"

### ISSUE THREAD

**Issue by adamalfredsson** [FullHuman/purgecss#838]
### Describe the bug

When purging my `.pug` files, I notice the class declared before `&attributes` is always purged.

### To Reproduce

I have this pug file:

```pug
mixin card
  .text-blue.text-center&attributes(attributes)
    block

+card
```

With this css:

```css
.text-blue {
  color: blue;
}

.text-center {
  text-align: center;
}
```

When purged, I get this css:

```css
.text-blue {
  color: blue;
}
```

### Expected Behavior

I expect `.text-center` to not have been purged.

### Environment

purgecss@2.3.0

### Add any other context about the problem here

Used by tailwind@1.9.6

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
